"""
通用命令执行工具

模仿 OpenClaw 的 exec 工具，允许 AI 执行任意命令
"""
import asyncio
import os
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from typing import Any

from agno.tools import tool

from utils.log_util import logger

# 创建线程池用于执行同步命令
_executor = ThreadPoolExecutor(max_workers=4)

# AI 对话生成文件的默认输出目录
AI_OUTPUT_DIR = os.path.join(os.getcwd(), 'ai_output')

# 确保输出目录存在
os.makedirs(AI_OUTPUT_DIR, exist_ok=True)


# 原始函数实现（可以直接调用）
async def _execute_command_impl(
    command: str,
    cwd: str | None = None,
    timeout: int = 30,
) -> str:
    """
    执行 shell 命令的内部实现
    
    Args:
        command: 要执行的 shell 命令
        cwd: 可选的工作目录（默认使用 AI_OUTPUT_DIR）
        timeout: 超时时间（秒）
    
    Returns:
        命令输出（stdout 和 stderr 合并）
    """
    def _run_command():
        """在线程池中执行命令"""
        try:
            logger.info(f'🔧 [工具调用] execute_command')
            logger.info(f'📝 [命令] {command}')
            
            # 如果没有指定工作目录，使用 AI 输出目录
            working_dir = cwd or AI_OUTPUT_DIR
            logger.info(f'📁 [工作目录] {working_dir}')
            
            # 确保工作目录存在
            if not os.path.exists(working_dir):
                os.makedirs(working_dir, exist_ok=True)
                logger.info(f'📁 [创建目录] {working_dir}')
            
            # 在 Windows 上使用 cmd，在 Unix 上使用 sh
            if os.name == 'nt':
                # Windows - 添加 chcp 65001 设置 UTF-8 编码
                shell_cmd = ['cmd', '/c', 'chcp 65001 >nul && ' + command]
            else:
                # Unix/Linux/Mac
                shell_cmd = ['sh', '-c', command]
            
            logger.info(f'⏳ [执行中] 正在运行命令...')
            
            # 使用同步的 subprocess（避免 NotImplementedError）
            process = subprocess.Popen(
                shell_cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                cwd=working_dir,
                text=True,
                encoding='utf-8',
                errors='replace'
            )
            
            try:
                output, _ = process.communicate(timeout=timeout)
                
                if process.returncode != 0:
                    logger.warning(f'⚠️  [失败] 命令返回非零退出码: {process.returncode}')
                    logger.warning(f'📄 [输出] {output[:500]}...' if len(output) > 500 else f'📄 [输出] {output}')
                    return f'Command failed (exit code {process.returncode}):\n{output}'
                
                logger.info(f'✅ [成功] 命令执行完成')
                logger.info(f'📄 [输出长度] {len(output)} 字符')
                return output or '(Command completed with no output)'
                
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait()
                error_msg = f'Command timed out after {timeout} seconds'
                logger.error(f'⏱️  [超时] {error_msg}')
                return f'Error: {error_msg}'
                
        except Exception as e:
            error_msg = f'Failed to execute command: {type(e).__name__}: {str(e)}'
            logger.error(f'❌ [异常] {error_msg}')
            logger.error(f'📝 [命令] {command}')
            logger.error(f'📁 [工作目录] {working_dir}')
            logger.error(f'🔍 [详情] {repr(e)}', exc_info=True)
            return f'Error: {error_msg}'
    
    # 在线程池中执行，避免阻塞事件循环
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(_executor, _run_command)


# 工具版本（供 Agent 调用）
@tool
async def execute_command(
    command: str,
    cwd: str | None = None,
    timeout: int = 30,
) -> str:
    """
    Execute a shell command and return its output.
    
    Use this tool when you need to run CLI commands, scripts, or programs.
    The command will be executed in a shell environment with access to
    system binaries and installed packages.
    
    IMPORTANT: Files generated by commands will be saved to the 'ai_output' directory
    by default. When generating files (like PPT, Excel, etc.), they will be placed
    in this directory automatically.
    
    Args:
        command: The shell command to execute (e.g., "python script.py --arg value")
        cwd: Optional working directory for command execution (defaults to ai_output directory)
        timeout: Maximum execution time in seconds (default: 30)
    
    Returns:
        The command output (stdout and stderr combined)
    
    Examples:
        - execute_command("python -m pip list")
        - execute_command("python scripts/generate.py --output result.txt")
        - execute_command("ls -la")
    """
    return await _execute_command_impl(command, cwd, timeout)


# 原始函数实现（可以直接调用）
async def _execute_python_code_impl(
    code: str,
    timeout: int = 30,
) -> str:
    """
    执行 Python 代码的内部实现
    
    Args:
        code: 要执行的 Python 代码
        timeout: 超时时间（秒）
    
    Returns:
        代码输出（stdout 和 stderr 合并）
    """
    def _run_python():
        """在线程池中执行 Python 代码"""
        try:
            logger.info(f'🐍 [工具调用] execute_python_code')
            logger.info(f'📝 [代码长度] {len(code)} 字符')
            
            # 使用当前 Python 解释器
            python_cmd = sys.executable
            logger.info(f'🔧 [解释器] {python_cmd}')
            logger.info(f'⏳ [执行中] 正在运行 Python 代码...')
            
            # 使用同步的 subprocess（避免 NotImplementedError）
            process = subprocess.Popen(
                [python_cmd, '-c', code],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                encoding='utf-8',
                errors='replace'
            )
            
            try:
                output, _ = process.communicate(timeout=timeout)
                
                if process.returncode != 0:
                    logger.warning(f'⚠️  [失败] Python 代码返回非零退出码: {process.returncode}')
                    logger.warning(f'📄 [输出] {output[:500]}...' if len(output) > 500 else f'📄 [输出] {output}')
                    return f'Python code failed (exit code {process.returncode}):\n{output}'
                
                logger.info(f'✅ [成功] Python 代码执行完成')
                logger.info(f'📄 [输出长度] {len(output)} 字符')
                return output or '(Code completed with no output)'
                
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait()
                error_msg = f'Python code timed out after {timeout} seconds'
                logger.error(f'⏱️  [超时] {error_msg}')
                return f'Error: {error_msg}'
                
        except Exception as e:
            error_msg = f'Failed to execute Python code: {type(e).__name__}: {str(e)}'
            logger.error(f'❌ [异常] {error_msg}')
            logger.error(f'📝 [代码长度] {len(code)} 字符')
            logger.error(f'🔍 [详情] {repr(e)}', exc_info=True)
            return f'Error: {error_msg}'
    
    # 在线程池中执行，避免阻塞事件循环
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(_executor, _run_python)


# 工具版本（供 Agent 调用）
@tool
async def execute_python_code(
    code: str,
    timeout: int = 30,
) -> str:
    """
    Execute Python code and return its output.
    
    Use this tool when you need to run Python code snippets directly.
    The code will be executed in a Python interpreter with access to
    standard library and installed packages.
    
    Args:
        code: The Python code to execute
        timeout: Maximum execution time in seconds (default: 30)
    
    Returns:
        The code output (stdout and stderr combined)
    
    Examples:
        - execute_python_code("print('Hello, World!')")
        - execute_python_code("import sys; print(sys.version)")
    """
    return await _execute_python_code_impl(code, timeout)
